// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'supabase_option.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_PROD_ANDROID_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_PROD_ANDROID_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_PROD_MESSAGING_SENDER_ID'] ?? '',
    projectId: dotenv.env['FIREBASE_PROD_PROJECT_ID'] ?? '',
    storageBucket: dotenv.env['FIREBASE_PROD_STORAGE_BUCKET'] ?? '',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_PROD_IOS_API_KEY'] ?? '',
    appId: dotenv.env['FIREBASE_PROD_IOS_APP_ID'] ?? '',
    messagingSenderId: dotenv.env['FIREBASE_PROD_MESSAGING_SENDER_ID'] ?? '',
    projectId: dotenv.env['FIREBASE_PROD_PROJECT_ID'] ?? '',
    storageBucket: dotenv.env['FIREBASE_PROD_STORAGE_BUCKET'] ?? '',
    iosClientId: dotenv.env['FIREBASE_PROD_IOS_CLIENT_ID'] ?? '',
    iosBundleId: dotenv.env['FIREBASE_PROD_IOS_BUNDLE_ID'] ?? '',
  );
}
