include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/l10n/*.dart
    - lib/gen/*.dart
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    sort_pub_dependencies: false
    use_build_context_synchronously: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false
    use_setters_to_change_properties: false