targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true # false -> true
      freezed:
        generate_for:
          include:
            - lib/model/entities/*.dart
            - lib/model/entities/**/*.dart
            - lib/model/use_cases/*.dart
            - lib/model/use_cases/**/*.dart
            - lib/results/*.dart