name: flutter_app_template
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.9

  # LocalDatabase
  shared_preferences: ^2.5.5

  # Riverpod
  hooks_riverpod: ^3.4.2
  riverpod_annotation: ^4.0.6

  # Hooks
  flutter_hooks: ^0.21.3

  # Api
  retrofit: 4.9.2
  dio: 5.11.0

  # Entity
  freezed_annotation: ^3.1.0

  # Launcher
  url_launcher: ^6.3.2

  # Image
  extended_image: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.8.0
  pedantic_mono: ^1.36.0
  json_serializable: ^6.14.1
  build_runner: ^2.16.0
  freezed: ^4.0.0-dev.3
  riverpod_generator: ^4.0.8
  retrofit_generator: ^10.2.8

dependency_overrides:
  meta: ^1.19.0
  test: ^1.31.2
  test_api: ^0.7.13

flutter:
  uses-material-design: true
